# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='date_modified',
            new_name='modified',
        ),
    ]
